version: 0.0
os: linux
files:
  - source: upload/
    destination: /opt/bitnami/apache2/htdocs
hooks:
  AfterInstall:
#    - location: scripts/install_dependencies
#      timeout: 300
#      runas: root
    - location: scripts/configure_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
